apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dropbox-clone-db-credentials
  namespace: dropbox-clone
spec:
  data:
    - secretKey: username
      remoteRef:
        key: dropbox-clone-prod-rds-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: dropbox-clone-prod-rds-credentials
        property: password
    - secretKey: host
      remoteRef:
        key: dropbox-clone-prod-rds-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: dropbox-clone-prod-rds-credentials
        property: port
    - secretKey: database
      remoteRef:
        key: dropbox-clone-prod-rds-credentials
        property: database
