apiVersion: v1
kind: ServiceAccount
metadata:
  name: dropbox-clone-api
  namespace: dropbox-clone
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::898769392027:role/dropbox-clone-dev-app-role
