apiVersion: v1
kind: ConfigMap
metadata:
  name: dropbox-clone-config
  namespace: dropbox-clone
  labels:
    app.kubernetes.io/name: dropbox-clone-api
    app.kubernetes.io/component: config
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  JWT_ISSUER: "dropbox-clone-api"
  JWT_ACCESS_TOKEN_TTL: "15m"
  JWT_REFRESH_TOKEN_TTL: "168h"
  S3_REGION: "us-east-1"
  LOG_LEVEL: "info"
