apiVersion: v1
kind: Service
metadata:
  name: dropbox-clone-api
  namespace: dropbox-clone
  labels:
    app.kubernetes.io/name: dropbox-clone-api
    app.kubernetes.io/component: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dropbox-clone-api
