apiVersion: v1
kind: ServiceAccount
metadata:
  name: dropbox-clone-api
  namespace: dropbox-clone
  labels:
    app.kubernetes.io/name: dropbox-clone-api
    app.kubernetes.io/component: api
  annotations:
    # IRSA annotation - will be patched per environment
    eks.amazonaws.com/role-arn: ""
